### ISSUE TITLE
Code folding does nothing

### ISSUE THREAD

**Issue by zerodivisionfeature** [fxbois/web-mode#397] opened 2015-01-02 22:15 UTC
I have tried installing web-mode from ELPA and github, none seems to do anything when trying to fold HTML tags:

Doing C-c C-f does nothing
and M-x web-mode-fold-or-unfold RET does nothing either, I can't say it has a wrong behaviour, 'couse no error or warning shows up. 
I'm running emacs 24.4.1 on Debian Gnu/Linux, any clues?

**Comment by fxbois** [comment] 2015-01-03 08:32
@poetamuerto you must be on a tag to fold an element

**Comment by poetamuerto** [comment] 2015-01-03 13:57
Still nothing, when I'm at the begining or inside the tag does nothing, and between opening and closing tag it says block-controls-get ** invalid value (2139 **...

Found this [link](http://bit.ly/13OEzHN] on OS but doesn't work for me.

**Comment by fxbois** [comment] 2015-01-03 15:18
@poetamuerto please post the output of ```M-x web-mode-debug```

**Comment by poetamuerto** [comment] 2015-01-03 21:07
M-x web-mode-debug RET

--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("10.1.29")
vars: engine("web2py") content-type("html") file("/home/marco/trabajo/experimental/web2py/applications/tpv2/views/layout.html")
system: window(x) config("x86_64-pc-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (transient-mark-mode line-number-mode auto-compression-mode auto-encryption-mode auto-composition-mode blink-cursor-mode font-lock-mode global-font-lock-mode file-name-shadow-mode mouse-wheel-mode electric-indent-mode tooltip-mode desktop-save-mode server-mode display-time-mode display-battery-mode display-lunar-phase-mode nyan-mode guru-mode guru-global-mode linum-mode global-linum-mode auto-complete-mode global-auto-complete-mode autopair-mode autopair-global-mode undo-tree-mode global-undo-tree-mode emmet-mode shell-dirtrack-mode)
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment] 2015-01-03 21:20
@poetamuerto and could you post your example on gist please

**Comment by poetamuerto** [comment] 2015-01-04 04:42
[Here](https://gist.github.com/poetamuerto/c1c07cc2cd04bb35e3b2) is the
gist file, and by creating the new file a have noticed that when
creating a new HTML file throws this message:

File mode specification error: (invalid-function (lamda nil
(autopair-mode -1)))

so, I guess something is messing my setup...

**Comment by fxbois** [comment] 2015-01-04 09:31
You should a try with a very "light" .emacs

**Comment by poetamuerto** [comment] 2015-01-05 05:54
Ok, now I have tested it, not sure if it is the intended behaviour but folding only works with cursor at the very begining of the line, not next or inside tags... so I guess nevermind, my bad about this issue.

**Comment by fxbois** [comment] 2015-01-05 07:14
@poetamuerto should work anywhere inside a tag

**Comment by poetamuerto** [comment] 2015-01-05 11:16
ok, then something must be wrong, on Emacs 24.4.1 tried ELPA version and github version with nothing more than web-mode in init.el and for me both behave the same. I'll try to dig deeper on this.

**Comment by madhat2r** [comment] 2015-01-23 18:22
I have same issue as @peleteiro

**Comment by fxbois** [comment] 2015-01-23 18:26
Please take a video and post it here. Insert also the output of web-mode-debug

**Comment by madhat2r** [comment] 2015-01-23 19:06
Not sure how to upload a video on here, but below is the output. I have  a small screen cast recorded so let me know how to upload it to here and I will do so. Thanks!

--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("10.2.04")
vars: engine("none") content-type("html") file("/mnt/inetpub/wwwroot/NewSite_Statebar/Statebar/CLE/staff/index.html")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg(nil) bg(nil) 
minor modes: (transient-mark-mode line-number-mode auto-compression-mode auto-encryption-mode auto-composition-mode blink-cursor-mode font-lock-mode global-font-lock-mode file-name-shadow-mode mouse-wheel-mode electric-indent-mode tooltip-mode delete-selection-mode show-paren-mode evil-local-mode undo-tree-mode global-undo-tree-mode evil-mode evil-leader-mode yas-minor-mode yas-global-mode auto-complete-mode global-auto-complete-mode diff-auto-refine-mode emmet-mode evil-matchit-mode global-evil-matchit-mode evil-surround-mode global-evil-surround-mode ido-everywhere flx-ido-mode ido-vertical-mode ido-ubiquitous-mode ac-js2-mode linum-mode global-linum-mode projectile-mode projectile-global-mode rainbow-delimiters-mode smartparens-mode smartparens-global-mode tern-mode)
--- WEB-MODE DEBUG END ---

**Comment by poetamuerto** [comment] 2015-01-23 19:55
try youtube and paste the link.

**Comment by madhat2r** [comment] 2015-01-23 20:04
Video

http://youtu.be/TJfrqE06-yE

**Comment by fxbois** [comment] 2015-01-23 21:02
@madhat2r the video was useful
the issue triggers when you have ```web-mode-enable-current-element-highlight``` enabled
I'll look at this

**Comment by fxbois** [comment] 2015-01-23 21:24
@poetamuerto @madhat2r please check the last version on github

**Comment by madhat2r** [comment] 2015-01-23 21:41
@fxbois That did if for me. 

Thanks for your hard work!

**Comment by poetamuerto** [comment] 2015-01-24 12:19
@fxbois it did worked!, thank you a lot!

**Comment by pascalhaakmat** [comment] 2016-12-06 12:59
Thanks for web-mode, I just installed it from github and it looks promising! I did run into an issue with folding that seems related to the above. C-c C-f gives an error ("block-controls-get ** invalid value (number) **") when the cursor is immediately AFTER a tag. 

For example (◼️ = cursor position):

<div>◼️
    <span>text</span>
</div>

Then hitting C-c C-f triggers the error. I would expect it to fold the outer <div>. 
Not a big deal, but perhaps something to review.

**Comment by fxbois** [comment] 2017-02-11 21:56
@pascalhaakmat should be better with last commit

**Closed by fxbois** 2017-02-11 21:56 UTC
Labels: command

**Comment by ramblehead** [comment] 2017-02-14 15:38
I recently found that nXML mode is no more sufficient for my HTML needs (after moving to HTML5) and discovered web-mode. It is brilliant! Thank you for sharing it!

While setting it up for code folding I came across this thread. The C-c C-f worked out of the box for me. However, it did not work for embedded JavaScript, so I had to setup hs-minor-mode as well. Then, the folded web-mode and hs-minor-mode code parts looked inconsistent and required different keystrokes to toggle folding in HTML and JavaScript. So, after some research I came up with a few small functions which do all code folding using hs-minor-mode with help from web-mode:

```elisp
(defun rh-web-hs-html ()
  ;; hs-forward-sexp-func is equal to web-mode-forward-sexp by default
  ;; hs-adjust-block-beginning is nil by default
  (setq hs-block-start-regexp "<!--\\|<[^/][^>]*[^/]>")
  (setq hs-block-end-regexp "-->\\|</[^/>]*[^/]>")
  (setq hs-c-start-regexp "<!--"))

(defun rh-web-hs-default ()
  (setq hs-block-start-regexp "{")
  (setq hs-block-end-regexp "}")
  (setq hs-c-start-regexp "/[*/]"))

(defun rh-web-hs-html-toggle-hiding ()
  (interactive)
  (rh-web-hs-html)
  (hs-toggle-hiding))

(defun rh-web-hs-toggle-hiding ()
  (interactive)
  (let ((web-mode-cur-language (web-mode-language-at-pos)))
    (if (string= web-mode-cur-language "html")
        (progn
          (rh-web-hs-html)
          (hs-toggle-hiding))
      (progn
        (if (string-match
             (concat "^[[:space:]]*<[^/][^>]*[^/]>[[:space:]]*$"
                     "\\|"
                     "^[[:space:]]*</[^/>]*[^/]>[[:space:]]*$")
             (thing-at-point 'line t))
            (rh-web-hs-html)
          (rh-web-hs-default))
        (hs-toggle-hiding)))))
```

A keystroke like in Dreamweaver:
```elisp
(local-set-key (kbd "C-S-j") 'rh-web-hs-toggle-hiding)
```

and another one if we would like to fold HTML tag while in e.g. embedded JavaScript:
```elisp
(local-set-key (kbd "C-x C-S-j") 'rh-web-hs-html-toggle-hiding)
```

The same approach should, probably, work for other languages.

**Comment by fxbois** [comment] 2017-02-14 15:57
@ramblehead thx for sharing !

**Comment by ramblehead** [comment] 2017-02-14 17:06
Another small observation with both ```C-c C-p``` folding and with my ```hs-minor-mode``` solution: neither of them folds HTML comment blocks ```<!--...-->```

The problem seems to be with ```web-mode-forward-sexp``` function as it does not go from ```<!--``` to ```-->``` as, perhaps, it should.

When in my code above I add

```elisp
(setq hs-forward-sexp-func 'sgml-skip-tag-forward)
```

to ```rh-web-hs-html``` function, and

```elisp
(setq hs-forward-sexp-func 'web-mode-forward-sexp)
```

to ```vr-web-hs-default``` function, the HTML comment blocks fold as expected. But then we are bring ```sgml-mode``` dependency which might have side effects with folding "non pure HTML" templates...

**Comment by fxbois** [comment] 2017-02-14 17:08
@ramblehead could you open a specific issue for html comment folding please
