### ISSUE TITLE
Syntax highlighting and tabbing being lost

### ISSUE THREAD

**Issue by grovermind** [fxbois/web-mode#393] opened 2014-12-30 21:10 UTC
I am encountering a problem where the syntax highlighting and tabbing for a file stops working frequently. For instance, in one file that I have, if I paste in particular a block of PHP code from somewhere else in the file, the highlighting and tabbing stops working seemingly every time when I attempt to tabify (highlight and press TAB). If I then try to tabify the entire file, all tabbing is removed, and when I type or modify a line, all the text is white. This persists for the same file in a new session of emacs.

I don't know if this would be helpful, but the following is in my .emacs mode related to tabbing/web mode.

(setq-default c-basic-offset 4
			  tab-width 4
			  indent-tabs-mode nil)

(defun my-web-mode-hook ()
  "Hooks for Web mode."
  (setq web-mode-markup-indent-offset 4)
  (setq web-mode-code-indent-offset 4)
  )
(add-hook 'web-mode-hook  'my-web-mode-hook)
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.php$" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[gj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))

**Comment by victorfence** [comment] 2015-01-08 07:02
I have this problem also, I can easilly reproduce this, such as in any html with a script tag in it. after file loaded, edit the content in the script tag, the content ouside scripte tag lost highlight at once, if i go on,  content inside script may also lost highlight, I must revert buffer to get highlight back, as below

origin
![0001](https://cloud.githubusercontent.com/assets/5809458/5659056/6819661a-9703-11e4-9638-d17524c0c46c.png)

hit enter
![0002](https://cloud.githubusercontent.com/assets/5809458/5659055/681481ae-9703-11e4-8ed6-84df89091cdb.png)

hit enter again
![0003](https://cloud.githubusercontent.com/assets/5809458/5659086/e36c07f0-9703-11e4-9421-d1e6352c9101.png)

my debug info:
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("9.0.16")
vars: engine(nil) content-type("") file(" *Minibuf-1*")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg("#ccc") bg("#222") 
modes: whitespace-mode(nil) global-whitespace-mode(nil) rainbow-mode(nil) idle-highlight-mode(nil) fic-mode(nil)
(transient-mark-mode auto-fill-function line-number-mode column-number-mode auto-compression-mode auto-encryption-mode auto-composition-mode blink-cursor-mode global-font-lock-mode file-name-shadow-mode mouse-wheel-mode electric-indent-mode tooltip-mode jabber-activity-mode tabbar-mode tabbar-mwheel-mode shell-dirtrack-mode yas/global-mode desktop-save-mode winner-mode auto-image-file-mode window-number-mode recentf-mode)
--- WEB-MODE DEBUG END ---

**Comment by victorfence** [comment] 2015-01-08 07:12
I have this problem also, after update to 10.2.00, the problem seems gone, but slow editing in buffers with just hundreds of lines. 

my debug info:
--- WEB-MODE DEBUG BEG ---
versions: emacs(24.4) web-mode("10.2.00")
vars: engine("none") content-type("html") file("/home/fcl/edx_all/edx-platform/lms/templates/reg_kits/course_permission.html")
system: window(x) config("x86_64-unknown-linux-gnu")
colors: fg("#ccc") bg("#222") 
minor modes: (transient-mark-mode auto-fill-function line-number-mode column-number-mode auto-compression-mode auto-encryption-mode auto-composition-mode blink-cursor-mode font-lock-mode global-font-lock-mode file-name-shadow-mode mouse-wheel-mode electric-indent-mode tooltip-mode jabber-activity-mode tabbar-mode tabbar-mwheel-mode shell-dirtrack-mode show-paren-mode yas/minor-mode yas/global-mode desktop-save-mode winner-mode highlight-parentheses-mode auto-image-file-mode window-number-mode recentf-mode)
--- WEB-MODE DEBUG END ---

**Comment by fxbois** [comment] 2015-01-08 07:14
@victorfence please post this buffer on gist and describe how to trigger the slowness

**Comment by victorfence** [comment] 2015-01-08 07:45
@fxbois 
I post a file about 600 lines, I can feel mush slow in it then in a small file (e.g. less then 100 lines) obviously.
https://gist.github.com/victorfence/46bb3de785466895c290

to trigger the slowness, no more, just typing anywherer, content comes out slowly.

**Comment by fxbois** [comment] 2015-01-08 19:21
@victorfence it is perhaps related to some minor mode ... could you try with an empty .emacs
I do feel any slowness (and my computer is quite old)

**Comment by victorfence** [comment] 2015-01-09 04:09
@fxbois Hi, I found the reason, I defind a hi-lock to highlight someting long time ago, this cause the slowness, now I get the very fast speed :) , sorry for bug you and thanks for writing this awsome mode!

**Comment by grovermind** [comment] 2015-01-09 12:44
After pulling the latest version the original issue with syntax highlighting being lost still occurs for me if I follow the same steps shown in the gist I posted.

**Comment by fxbois** [comment] 2015-01-09 13:44
Have you tried with an empty.emacs?

**Comment by grovermind** [comment] 2015-01-09 15:54
I temporarily renamed my emacs and was able to reproduce the issue with the code sample shown in the gist I posted.
![screenshot from 2015-01-09 10 52 58](https://cloud.githubusercontent.com/assets/2747644/5682410/df629120-97ed-11e4-9b76-c6abec4452df.png)

**Comment by fxbois** [comment] 2015-01-09 21:41
@grovermind imposible for me to trigger this issue. Could you try to take a little video ?

**Comment by grovermind** [comment] 2015-01-13 20:13
Here is a video of the issue occurring. After the syntax highlighting is lost, I am pressing tab at the beginning of the lines, which is also causing the tabbing to be lost. Please let me know if you need to see more. Seems like a sticky problem.

https://drive.google.com/file/d/0B_OqfhSRFsfMbU9VZ1VFUy05c2c/view?usp=sharing

**Comment by fxbois** [comment] 2015-01-13 23:23
@grovermind thx, it was useful, I ve managed to trigger the issue. I'll work on this

**Comment by fxbois** [comment] 2015-01-14 06:57
@grovermind I've pushed a fix

**Comment by grovermind** [comment] 2015-01-14 13:51
When I try the steps the created the bug, syntax highlighting now remains, but I cannot get the auto-tabbing to complete until I reload web-mode.
![screenshot from 2015-01-14 08 49 51](https://cloud.githubusercontent.com/assets/2747644/5739722/864fad8a-9bca-11e4-8cb5-05d87cbf627d.png)

**Comment by fxbois** [comment] 2015-01-14 13:54
@grovermind are you sure you have the last version on github ?
If yes, could you post an other video please

**Comment by grovermind** [comment] 2015-01-14 14:04
My mistake, I think. I loaded the new package but I did not restart emacs. Upon doing so I cannot reproduce the bug with version 20150114.337. I don't know how to tell if that is the same as the most recent github version, but I assume it is.

**Closed** 2015-01-14 15:30 UTC
Labels: bug
